---
title: "Sampling Frame Descriptives"
output: 
  html_document: 
    df_print: kable
    theme: journal
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE)

################## READ ME #################################

  ## Step 1
  ### Enter main directory paths to proper folder
  ### Manually `Run Setup Chunk`

  ## Step 2
  ### Enter filenames in `wrangle data` chunk
  
  ## Step 3 
  ### Run `clean data` chunk

  ## Step 4 (to create report)
  ### copy and run render function in console:
  
  ## rmarkdown::render("DOC/DIRECTORY/DataPull_*.Rmd", output_file = paste0("REPORTNAME_",today(),".html"), output_format = "all", output_dir = paste0(studypath,"Reports/")) 

#########################################################


library(tidyverse)
library(readxl)
library(lubridate)
library(openxlsx)
library(knitr)
library(sf)

### set path variables
xpath <<- "ENTER/LONG/XDRIVE/DIRECTORY/FOR/DATAPULL/LOCATION/"

studypath <<- "ENTER/LONG/XDRIVE/DIRECTORY/FOR/STUDY/FOLDER/"


wrangler <- function(x,arg1,arg2){  #### wrangle raw data ####
  
  ## col types 
  names <- names(read_excel(paste0(xpath,x), n_max = 0))
    ct <- ifelse(grepl("^VisitDateTime_", names), "date", ifelse(grepl("^PatientSSN", names), "text", "guess"))
  ## import data
  raw <- read_excel(paste0(xpath,x), col_types = ct)

  ## import all screens
  AU <- read_excel(paste0(xpath,arg1)) %>% 
    mutate(ScreenDate_AU = date(VisitDateTime), AUDC=as.numeric(RawScore)) %>%
    select(PatientSID, ScreenDate_AU, AUDC) %>%
    group_by(PatientSID) %>% slice(which.max(ScreenDate_AU))
  
  PS <- read_excel(paste0(xpath,arg2)) %>% 
    mutate(ScreenDate_PS = date(VisitDateTime), PCPTSD =as.numeric(RawScore)) %>%
    select(PatientSID, ScreenDate_PS, PCPTSD) %>%
    group_by(PatientSID) %>% slice(which.max(ScreenDate_PS))
  
  all_screens <- merge(AU, PS, by.x = "PatientSID", by.y = "PatientSID", all = TRUE)
  
  ## merge to master file
  merged <<- merge(raw,all_screens, by.x = "PatientSID", by.y = "PatientSID", all.x = TRUE)
  ## save raw data to study folder
  merged  %>% write.xlsx(paste0(studypath,"FOLDER/filename_",today(),"_RAW.xlsx"))
}

  
#### clean data pull ####
clean_datapull <- function(x){  
 
  clean <-x %>% select(-PatientName) %>% 
    separate(PatientFirstName, into = c("First_Name", "Middle", "suffix")) %>%
    replace_na(list(suffix = "")) %>%
    unite(Last_Name, PatientLastName, suffix, sep = " ") %>%
     unite(First_Name, First_Name, Middle, sep = " ") %>% 
    mutate(ScreenID = "", subnum = "",Study = "PC-TIME", List_Date = today(),
         SignOff_Date = "", Next_Contact = "", Recruitment_Status = "Pending PCP Sign-Off",
         CheckBack_Date = "") %>% 
    rename(PCP = PrimaryCareProvider,PC_Type =ProviderType, SSN = PatientSSN) %>%
    select(-PatientSID,-c(16:22))

 ### Study specific 
  ## order columns
  newclean <- cbind(clean[27:28], clean[1:2],clean[16],clean[29:34],clean[11:14],clean[26],
                    clean[17:18],clean[15],clean[22:25], clean[3:10],clean[19:21]) %>% 
    as.tibble()

  ## create sheet 1 - Patient info
  sheet1 <<- newclean %>% 
    rename(Eligibility = Eligible_AUDC_PTSD_BOTH) %>%
    select(-c(24:34))

  ## calculate distance to VA
  VA <- read_excel(paste0(studypath,"VA_geo.xlsx")) %>%
    st_as_sf(coords = c("long","lat"), crs = 4269)

  newclean$lat <- ifelse(newclean$GISPatientAddressLatitude == 0, NA, newclean$GISPatientAddressLatitude)
  newclean$long <- ifelse(newclean$GISPatientAddressLongitude == 0, NA, newclean$GISPatientAddressLongitude)

  geoloc <- newclean %>% 
    select(Site, SSN,long,lat) %>%  na.omit() %>% 
    st_as_sf(coords = c("long","lat"), crs = 4269)

  VA_dist <- map(c("SiteName1",...), function(x){
    city <-geoloc %>% filter(Site == x)
    site <- filter(VA, Site == x)
    dist <- st_distance(city,site)
    out <- mutate(city, dist = dist)
    return(out)
  }) %>%
    reduce(rbind) %>%
    select(-Site)

  ## create sheet 2 - Address info
  sheet <- newclean %>% 
    select(Last_Name, SSN, Home_Phone = "PhoneNumber1", Cell_Phone = "PhoneNumber2",StreetAddress1,
           StreetAddress2, City, State, Zip,lat,long,Site) %>% 
    replace_na(list(StreetAddress2 = "")) %>% 
    unite(StreetAddress, StreetAddress1,StreetAddress2, sep = " ") %>% 
    mutate(Call_Text = "", Notes = "", Staff = "")

  sheet2 <<- left_join(sheet,VA_dist, by = "SSN") %>% 
    mutate(dist_miles = as.numeric(dist/1609.34), dist_meters = as.numeric(dist)) %>% 
    select(1:14, 17:18)

  ## create workbook
  two_sheets <- list("Patient Info" = sheet1, "Address Info" = sheet2)
  write.xlsx(two_sheets, paste0(studypath,"FOLDER/filename_",today(),".xlsx"))
}

```


```{r wrangle data}

## Enter raw data filenames 
## include a `.xlsx` extension  

## x - master data pull
master <- "filename.xlsx" 

## arg1 - AU scores
screens_au <- "filename.xlsx"

## arg2 - PT scores
screens_ps <- "filename.xlsx"

## do not change
wrangler(master,screens_au,screens_ps) ## run function 
    
```


```{r Edit PC Teams}

merged$PC_Team <- gsub("\\d", "",str_remove(merged$`PC Team`,"TEAMLET")) %>%
  str_remove(" A") %>% str_wrap()

```


```{r clean data}

## do not change
clean_datapull(merged) ## run function 

```

## Sample size by Site

```{r}
sheet1 %>% group_by(Site) %>% summarise(count = n())

sheet1 %>% group_by(Site) %>% summarise(count = n()) %>%
  ggplot(aes(Site, count)) + geom_col(fill="grey50") + labs(x = "") +
  theme_minimal() + theme(axis.text = element_text(color = "black")) 
```

## Women's Sample

```{r}

sheet1 %>%filter(Gender == "F") %>% group_by(Site, Eligibility) %>% 
  summarise(Count = n()) %>% 
  ggplot(aes(Site, Count, fill = fct_relevel(Eligibility, "BOTH"))) + geom_col(position = "dodge") + 
  labs(x = "", fill = "Positive Screens:") +
  theme_minimal() + theme(axis.text = element_text(color = "black"), legend.position = "bottom") +
  scale_fill_viridis_d(option = "cividis")

```

## Primary Care Screens

```{r}

sheet1 %>% filter(PCPTSD > 0) %>%
  mutate(group = ifelse((PCPTSD >= 2), "Positive PC-PTSD", "Negative PC-PTSD")) %>%
  group_by(Site, Gender, group) %>% summarise(count = n()) %>%
  spread(group,count)

sheet1 %>% filter(PCPTSD > 0) %>%
  mutate(group = ifelse((PCPTSD >= 2), "Positive PC-PTSD", "Negative PC-PTSD")) %>%
  ggplot(aes(Site, AUDC)) + geom_boxplot(aes(color = Gender)) + 
  theme_minimal() + 
  theme(axis.text = element_text(color = "black"), legend.position = "bottom", 
        panel.spacing = unit(2, "lines"), strip.text.x = element_text(color = "black", face = "bold")) + labs(x = "") + 
  geom_hline(yintercept = 3, linetype = "dashed", color = "black") +
  scale_color_viridis_d(option = "cividis") + facet_grid(~group) 

```

## Counts when positive for both screens 

```{r Screen both}

sheet1 %>% filter(Eligibility == "BOTH")  %>% 
   group_by(Site, Gender) %>% summarise(count = n(),AUD_median = median(AUDC),
                                AUDC_max = max(AUDC),PTSD_median = median(PCPTSD),
                                PCPTSD_max = max(PCPTSD))
```


```{r both plot}

sheet1 %>% group_by(Month= month(ScreenDate_AU, label = TRUE), Site) %>% 
  filter(Eligibility == "BOTH") %>% summarise(count = n()) %>% 
  ggplot(aes(x = as.factor(Month),count, color = Site, group = Site)) + 
  geom_line() + geom_point() + labs(x = "2018", y = "Number of patients") +
  theme_minimal() + theme(axis.text = element_text(color = "black")) + 
  scale_color_viridis_d() + scale_y_continuous(breaks = c(2,4,6,8, 10))

```


## Average distance to site
```{r distance}

sheet2 %>% select(Site, dist_miles) %>% filter(dist_miles > 0 & dist_miles < 25) %>%
   group_by(Site) %>% summarise(Count = n(), Avg. = mean(dist_miles))

sheet2 %>% select(Site, dist_miles) %>% filter(dist_miles > 0 & dist_miles < 25) %>%
  ggplot(aes(Site, dist_miles)) + geom_boxplot() + theme_minimal() +
  theme(axis.text = element_text(color = "black")) +
  labs(y = "Distance in miles", x = "")

```

### Patients with permanent out-of-state address
```{r}
sheet2 %>% filter(State != "NEW YORK") %>% 
   group_by(Site) %>% summarise(Count = n())

```

## Counts by PC Team

```{r teams}

clinic_count <-  function(x){sheet1 %>% filter(Site== x) %>% group_by(Site, PC_Team) %>%
    summarise(count = n()) %>% arrange(desc(count))}

```

### Site Name

```{r}

clinic_count("Site")

```







